#!/usr/bin/env bash
#
# verify-sd-build.sh
#
# Verification script for Stable Diffusion build infrastructure.
# Tests that all required components are in place for building with SD support.
#
# This script checks:
#   - Build scripts exist and are executable
#   - CMakeLists.txt is properly configured
#   - Header files are present or can be generated
#   - CGo bindings have correct build tags
#   - Documentation references are valid
#
# Usage:
#   ./verify-sd-build.sh
#
# Exit codes:
#   0 - All checks passed
#   1 - One or more checks failed

set -euo pipefail

# Constants
readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Colors
if [[ -t 1 ]]; then
    RED='\033[0;31m'
    GREEN='\033[0;32m'
    YELLOW='\033[1;33m'
    BLUE='\033[0;34m'
    NC='\033[0m'
else
    RED='' GREEN='' YELLOW='' BLUE='' NC=''
fi

# Counters
CHECKS_TOTAL=0
CHECKS_PASSED=0
CHECKS_FAILED=0
CHECKS_WARNED=0

log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[PASS]${NC} $1"
    CHECKS_PASSED=$((CHECKS_PASSED + 1))
}

log_fail() {
    echo -e "${RED}[FAIL]${NC} $1"
    CHECKS_FAILED=$((CHECKS_FAILED + 1))
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
    CHECKS_WARNED=$((CHECKS_WARNED + 1))
}

check_file_exists() {
    local file="$1"
    local description="$2"

    CHECKS_TOTAL=$((CHECKS_TOTAL + 1))

    if [[ -f "$file" ]]; then
        log_success "$description exists: $file"
        return 0
    else
        log_fail "$description missing: $file"
        return 1
    fi
}

check_file_executable() {
    local file="$1"
    local description="$2"

    CHECKS_TOTAL=$((CHECKS_TOTAL + 1))

    if [[ -x "$file" ]]; then
        log_success "$description is executable: $file"
        return 0
    else
        log_fail "$description not executable: $file"
        return 1
    fi
}

check_dir_exists() {
    local dir="$1"
    local description="$2"

    CHECKS_TOTAL=$((CHECKS_TOTAL + 1))

    if [[ -d "$dir" ]]; then
        log_success "$description exists: $dir"
        return 0
    else
        log_fail "$description missing: $dir"
        return 1
    fi
}

check_file_contains() {
    local file="$1"
    local pattern="$2"
    local description="$3"

    CHECKS_TOTAL=$((CHECKS_TOTAL + 1))

    if [[ ! -f "$file" ]]; then
        log_fail "$description: file not found ($file)"
        return 1
    fi

    if grep -q "$pattern" "$file"; then
        log_success "$description"
        return 0
    else
        log_fail "$description: pattern not found in $file"
        return 1
    fi
}

echo ""
echo "=============================================="
echo "  SD Build Infrastructure Verification"
echo "=============================================="
echo ""

# Check 1: Build scripts
log_info "Checking build scripts..."
check_file_exists "$SCRIPT_DIR/build-sd-linux.sh" "Linux build script"
check_file_executable "$SCRIPT_DIR/build-sd-linux.sh" "Linux build script"
check_file_exists "$SCRIPT_DIR/build-sd-windows.ps1" "Windows build script"

# Check 2: SD dependency directory
log_info "Checking stable-diffusion.cpp integration..."
check_dir_exists "$PROJECT_ROOT/deps/stable-diffusion.cpp" "SD dependency directory"
check_file_exists "$PROJECT_ROOT/deps/stable-diffusion.cpp/CMakeLists.txt" "SD CMakeLists.txt"
check_file_exists "$PROJECT_ROOT/deps/stable-diffusion.cpp/build-linux.sh" "SD Linux build script"
check_file_exists "$PROJECT_ROOT/deps/stable-diffusion.cpp/build-windows.ps1" "SD Windows build script"

# Check 3: CMakeLists.txt configuration
log_info "Checking CMakeLists.txt configuration..."
check_file_contains "$PROJECT_ROOT/deps/stable-diffusion.cpp/CMakeLists.txt" "GGML_CUDA" "CMake CUDA support enabled"
check_file_contains "$PROJECT_ROOT/deps/stable-diffusion.cpp/CMakeLists.txt" "BUILD_SHARED_LIBS" "CMake shared library option"
check_file_contains "$PROJECT_ROOT/deps/stable-diffusion.cpp/CMakeLists.txt" "CMAKE_CUDA_ARCHITECTURES" "CMake CUDA architectures defined"

# Check 4: Header files or generation capability
log_info "Checking SD header files..."
if [[ -f "$PROJECT_ROOT/deps/stable-diffusion.cpp/include/stable-diffusion.h" ]]; then
    check_file_exists "$PROJECT_ROOT/deps/stable-diffusion.cpp/include/stable-diffusion.h" "SD header file"
else
    CHECKS_TOTAL=$((CHECKS_TOTAL + 1))
    log_warn "SD header not present (will be generated by CMake)"
fi

# Check 5: CGo bindings
log_info "Checking CGo bindings..."
check_file_exists "$PROJECT_ROOT/sdruntime/cgo_bindings_sd.go" "CGo SD implementation"
check_file_exists "$PROJECT_ROOT/sdruntime/cgo_bindings_stub.go" "CGo stub implementation"

# Check 6: Build tags
log_info "Checking build tags..."
check_file_contains "$PROJECT_ROOT/sdruntime/cgo_bindings_sd.go" "//go:build sd && cgo && !stub" "CGo SD build tags"
CHECKS_TOTAL=$((CHECKS_TOTAL + 1))
if grep -q "//go:build.*!sd" "$PROJECT_ROOT/sdruntime/cgo_bindings_stub.go"; then
    log_success "CGo stub build tags"
else
    log_fail "CGo stub build tags: pattern not found in $PROJECT_ROOT/sdruntime/cgo_bindings_stub.go"
fi

# Check 7: CGo linking configuration
log_info "Checking CGo linking configuration..."
check_file_contains "$PROJECT_ROOT/sdruntime/cgo_bindings_sd.go" "LDFLAGS.*-lstable-diffusion" "CGo LDFLAGS for SD library"
check_file_contains "$PROJECT_ROOT/sdruntime/cgo_bindings_sd.go" "#include <stable-diffusion.h>" "CGo header include"

# Check 8: Documentation
log_info "Checking documentation..."
check_file_exists "$PROJECT_ROOT/docs/BUILD_WITH_SD.md" "SD build guide"
check_file_contains "$PROJECT_ROOT/README.md" "BUILD_WITH_SD.md" "README references SD build guide"

# Check 9: Supporting scripts (optional but recommended)
log_info "Checking supporting scripts..."
if [[ -f "$SCRIPT_DIR/build-sd-cuda.sh" ]]; then
    check_file_exists "$SCRIPT_DIR/build-sd-cuda.sh" "SD CUDA build helper (optional)"
fi

# Summary
echo ""
echo "=============================================="
echo "  Verification Summary"
echo "=============================================="
echo ""
echo "Total checks:   $CHECKS_TOTAL"
echo -e "Passed:         ${GREEN}$CHECKS_PASSED${NC}"
echo -e "Failed:         ${RED}$CHECKS_FAILED${NC}"
echo -e "Warnings:       ${YELLOW}$CHECKS_WARNED${NC}"
echo ""

if [[ $CHECKS_FAILED -gt 0 ]]; then
    echo -e "${RED}VERIFICATION FAILED${NC}"
    echo "Some required components are missing or incorrectly configured."
    echo "Please review the failed checks above."
    exit 1
elif [[ $CHECKS_WARNED -gt 0 ]]; then
    echo -e "${YELLOW}VERIFICATION PASSED WITH WARNINGS${NC}"
    echo "Optional components missing but build should work."
    exit 0
else
    echo -e "${GREEN}VERIFICATION PASSED${NC}"
    echo "All SD build infrastructure components are in place."
    exit 0
fi
